name: Despliegue

on:
  push:
    branches: [main]

jobs:
  build:
    name: 🐘 Desplegar
    runs-on: ubuntu-latest

    steps:
      - name: 🐯 Obtener código del repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🐝 Usar Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: 🦒 Instalar dependencias y hacer build
        run: |
          yarn install --frozen-lockfile
          yarn build
          with:
            local-dir: './publico/'
